### ISSUE TITLE
引入serialport依赖调用出现异常

### ISSUE THREAD

**Issue by likui887** [electron-vite/vite-plugin-electron#134]
1.本地环境 node：v16.19.1 操作系统：macos 
2.vite-plugin-electron 运行环境和版本: 使用的是主分支代码运行，package.json的dependencies 已经配置 "serialport": "^10.5.0"，vite.config.ts 配置没改动，工程不调用 serialport 方法时可以正常运行
3.复现代码:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/93627863/231109495-59fd3a65-a75a-46be-8a85-fbc4143b4ecb.png">

Uncaught Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=113 uv=1 armv=8 libc=glibc node=18.12.1 electron=23.2.2
    loaded from: /Users/xx/IdeaProjects/opensource/electron-vite-vue/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar

    at load.resolve.load.path (node-gyp-build.js:60:9)
    at load (node-gyp-build.js:22:30)
    at node_modules/@serialport/bindings-cpp/dist/load-bindings.js (load-bindings.js:11:38)
    at __require2 (chunk-OROXOI2D.js?v=75c3c704:16:50)
    at node_modules/@serialport/bindings-cpp/dist/darwin.js (darwin.js:8:25)
    at __require2 (chunk-OROXOI2D.js?v=75c3c704:16:50)
    at node_modules/@serialport/bindings-cpp/dist/index.js (index.js:23:18)
    at __require2 (chunk-OROXOI2D.js?v=75c3c704:16:50)
    at node_modules/serialport/dist/serialport.js (serialport.js:5:24)
    at __require2 (chunk-OROXOI2D.js?v=75c3c704:16:50)

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-vue/blob/3b766bd0b7b0706d98baede7e7701d2e43ad72da/vite.config.ts#L36
你看看这块代码，可以把 `serialport` 放到 `rollupOptions.external` 中绕开构建。

**Comment by likui-developer** [comment]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/93627863/231165581-f2c6db7c-14de-41ba-8926-945279b4e95b.png">
我已经将 `serialport`  放入了 `external ` 中还是在 `electron` 【程序启动后】调用`SerialPort.list()` 函数时出现了此异常，请问下在配置了`external`后还需不需要像 `webpack` 一样另外配置 ，这块不是很懂 `webpack` 配置如下：

  ```
  pluginOptions: {
         electronBuilder: {
            nodeIntegration: true,
            externals: ['serialport'],
            builderOptions: {
                ...
                },
            },
        }
  ```
