### ISSUE TITLE
TypeError: electron is not a function

### ISSUE THREAD

**Issue by Troublebreaker** [electron-vite/vite-plugin-electron#138]
I hav removed "type": "module" in package.json fix it. the error is still alive
```
{
  "name": "electron_vue_vite_electron",
  "private": true,
  "version": "0.0.0",
  "main": "electron/index.ts",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build && electron-builder",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.2.47"
  },
  "devDependencies": {
    "@types/node": "^18.16.3",
    "@vitejs/plugin-vue": "^4.1.0",
    "electron": "^24.1.3",
    "typescript": "^5.0.2",
    "vite": "^4.3.2",
    "vite-plugin-electron": "^0.11.2",
    "vue-tsc": "^1.4.2"
  }
}



```

vite.config.ts
```
const { defineConfig } = require("vite");
const vue = require("@vitejs/plugin-vue");
const electronPlugin = require("vite-plugin-electron");
const electron = require("electron");
const path = require("path");

const resolve = (dir: string) => path.join(__dirname, dir);

// https://vitejs.dev/config/
module.exports = defineConfig({
  plugins: [
    vue(),
    electron({
      main: {
        entry: "electron/index.ts",
      },
      electron: require("electron")
    }),
  ],
  resolve: {
    alias: {
      "@": resolve("src"),
    },
  },
});

```
My Error
```

failed to load config from /Users/caoliang/code/test/month3/electBest/myElectron/vite.config.ts
error when starting dev server:
TypeError: electron is not a function
    at Object.<anonymous> (/Users/caoliang/code/test/month3/electBest/myElectron/vite.config.ts:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object._require.extensions.<computed> [as .js] (file:///Users/caoliang/code/test/month3/electBest/myElectron/node_modules/vite/dist/node/chunks/dep-a178814b.js:64432:24)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigFromBundledFile (file:///Users/caoliang/code/test/month3/electBest/myElectron/node_modules/vite/dist/node/chunks/dep-a178814b.js:64440:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async loadConfigFromFile (file:///Users/caoliang/code/test/month3/electBest/myElectron/node_modules/vite/dist/node/chunks/dep-a178814b.js:64296:28)
```

**Comment by Troublebreaker** [comment]
I have resloved this problem, I should  follow the documention
