### ISSUE TITLE
求助： forge+vite+vue3 生成的项目，在渲染进程import报错

### ISSUE THREAD

**Issue by ddmy** [electron-vite/vite-plugin-electron#185]
![image](https://github.com/electron-vite/vite-plugin-electron/assets/19168372/14ae43fe-2e4e-4b56-8b6e-cec601b4c32b)

```
  "devDependencies": {
    "@electron-forge/cli": "^7.2.0",
    "@electron-forge/maker-deb": "^7.2.0",
    "@electron-forge/maker-rpm": "^7.2.0",
    "@electron-forge/maker-squirrel": "^7.2.0",
    "@electron-forge/maker-zip": "^7.2.0",
    "@electron-forge/plugin-auto-unpack-natives": "^7.2.0",
    "@electron-forge/plugin-vite": "^7.2.0",
    "@vitejs/plugin-vue": "^4.5.1",
    "electron": "27.1.3",
    "vite-plugin-electron": "^0.15.4"
  },
  "dependencies": {
    "electron-squirrel-startup": "^1.0.0",
    "element-plus": "^2.4.3",
    "vue": "^3.3.9"
  }
```

我这是一个新项目，学习研究使用。 我尝试在渲染进程打开一个额外的窗口，并尝试与主进程通信。
所以需要导入`electron`的方法，require在vite中不支持，使用import语法，就会报错误
```
Uncaught ReferenceError: __dirname is not defined
    at node_modules/electron/index.js (index.js:4:28)
    at __require (chunk-UXIASGQL.js?v=ad67e170:8:50)
    at index.js:21:34
```
```
const pathFile = path.join(__dirname, 'path.txt');
```

我现在需要通过[vite-plugin-electron](https://github.com/electron-vite/vite-plugin-electron)配置达到以下目的：
1. 在渲染进程能随意使用node api和electron api
2. 全局统一 导入语法 为import

[问题复现在线仓库](https://github.com/ddmy/ulink-vite-app)

小弟初学者，恳请各位大佬指点迷津。

**Comment by caoxiemeihao** [comment]
需要配合 `vite-plugin-electron-renderer` 使用，其次在主进程中开启 `nodeIntegration: true`
