### ISSUE TITLE
killtree in 0.28.2 causes crash

### ISSUE THREAD

**Issue by Kilian** [electron-vite/vite-plugin-electron#214]
after updating to 0.28.2 it crashes on startup on ubuntu 23.04 with the following error:

```sh
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error: kill ESRCH
    at process.kill (node:internal/process/per_thread:233:13)
    at killTree ([...]/node_modules/vite-plugin-electron/dist/index.js:147:11)
    at killTree [...]/node_modules/vite-plugin-electron/dist/index.js:144:7)
    at treeKillSync ([...]/node_modules/vite-plugin-electron/dist/index.js:126:5)
    at startup.exit ([...]/node_modules/vite-plugin-electron/dist/index.js:237:5)
    at startup ([...]/node_modules/vite-plugin-electron/dist/index.js:225:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -3,
  code: 'ESRCH',
  syscall: 'kill'
}
```

**Comment by DJWezzz** [comment]
Same on Windows 11

**Comment by bajelidze** [comment]
Same on Arch Linux. Although, I am getting `ErrnoException` instead of `ErrorCaptureStackTrace`.

Happens only on v0.28.2, doesn't happen on v0.28.1 or earlier. Using Vite 5.1.3.

<details>

<summary>Logs</summary>
```

> Ortomed@0.0.0 dev
> ELECTRON_ENABLE_LOGGING=1 NODE_OPTIONS='--unhandled-rejections=strict' vite

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more
details.
Re-optimizing dependencies because lockfile has changed

  VITE v5.1.3  ready in 151 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
vite v5.1.3 building for development...

watching for file changes...
vite v5.1.3 building for development...

watching for file changes...

build started...

build started... (x2)
✓ 4 modules transformed.
dist-electron/preload.js  6.93 kB │ gzip: 1.83 kB │ map: 12.39 kB
built in 136ms.
transforming (201) node_modules/ajv/dist/vocabularies/validation/index.js[60755:0218/225335.690357:WARNING:bluez_dbus_manager.cc(248)] F
loss manager not present, cannot set Floss enable/disable.
[60755:0218/225335.702104:WARNING:electron_api_native_image.cc(194)] Failed to load image from path '/home/ib/Code/ortomed/public/ortome
d.svg'
transforming (503) node_modules/winston/lib/winston/exception-handler.js[60755:0218/225335.981858:INFO:CONSOLE(467)] "[vite] connecting.
..", source: http://localhost:5173/@vite/client (467)
transforming (509) node_modules/winston/lib/winston/container.js[60755:0218/225336.125851:INFO:CONSOLE(572)] "[vite] connected.", source
: http://localhost:5173/@vite/client (572)
✓ 630 modules transformed.
dist-electron/main.js  1,183.30 kB │ gzip: 252.70 kB │ map: 2,345.22 kB
built in 1872ms.
[60755:0218/225337.495695:ERROR:command_buffer_proxy_impl.cc(319)] GPU state invalid after WaitForGetOffsetInRange.
[60755:0218/225337.497033:ERROR:network_service_instance_impl.cc(601)] Network service crashed, restarting service.
[60755:0218/225337.499866:ERROR:zygote_communication_linux.cc(290)] Failed to send GetTerminationStatus message to zygote
[60755:0218/225337.499874:WARNING:zygote_communication_linux.cc(302)] Socket closed prematurely.
[60755:0218/225337.501144:ERROR:gpu_process_host.cc(987)] GPU process launch failed: error_code=1002
[60755:0218/225337.501150:WARNING:gpu_process_host.cc(1363)] The GPU process has crashed 1 time(s)
[60755:0218/225337.501866:ERROR:gpu_process_host.cc(987)] GPU process launch failed: error_code=1002
[60755:0218/225337.501872:WARNING:gpu_process_host.cc(1363)] The GPU process has crashed 2 time(s)
[60755:0218/225337.502050:ERROR:gpu_process_host.cc(987)] GPU process launch failed: error_code=1002
[60755:0218/225337.502055:WARNING:gpu_process_host.cc(1363)] The GPU process has crashed 3 time(s)
[60755:0218/225337.502230:ERROR:gpu_process_host.cc(987)] GPU process launch failed: error_code=1002
[60755:0218/225337.502234:WARNING:gpu_process_host.cc(1363)] The GPU process has crashed 4 time(s)
[60755:0218/225337.502401:ERROR:gpu_process_host.cc(987)] GPU process launch failed: error_code=1002
[60755:0218/225337.502406:WARNING:gpu_process_host.cc(1363)] The GPU process has crashed 5 time(s)
[60755:0218/225337.502569:ERROR:gpu_process_host.cc(987)] GPU process launch failed: error_code=1002
[60755:0218/225337.502573:WARNING:gpu_process_host.cc(1363)] The GPU process has crashed 6 time(s)
[60755:0218/225337.502769:ERROR:gpu_process_host.cc(987)] GPU process launch failed: error_code=1002
[60755:0218/225337.502774:WARNING:gpu_process_host.cc(1363)] The GPU process has crashed 7 time(s)
[60755:0218/225337.502953:ERROR:gpu_process_host.cc(987)] GPU process launch failed: error_code=1002
[60755:0218/225337.502957:WARNING:gpu_process_host.cc(1363)] The GPU process has crashed 8 time(s)
[60755:0218/225337.503123:ERROR:gpu_process_host.cc(987)] GPU process launch failed: error_code=1002
[60755:0218/225337.503127:WARNING:gpu_process_host.cc(1363)] The GPU process has crashed 9 time(s)
[60755:0218/225337.503130:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
node:internal/process/per_thread:233
      throw new ErrnoException(err, 'kill');
            ^

Error: kill ESRCH
    at process.kill (node:internal/process/per_thread:233:13)
    at killTree (/home/ib/Code/ortomed/node_modules/vite-plugin-electron/dist/index.js:147:11)
    at killTree (/home/ib/Code/ortomed/node_modules/vite-plugin-electron/dist/index.js:144:7)
    at treeKillSync (/home/ib/Code/ortomed/node_modules/vite-plugin-electron/dist/index.js:126:5)
    at startup.exit (/home/ib/Code/ortomed/node_modules/vite-plugin-electron/dist/index.js:237:5)
    at startup (/home/ib/Code/ortomed/node_modules/vite-plugin-electron/dist/index.js:225:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -3,
  code: 'ESRCH',
  syscall: 'kill'
}

Node.js v21.6.1
```
</details>

**Comment by caoxiemeihao** [comment]
@Kilian Sorry I've been very busy lately, I'll spend a weekend trying to figure this out on Ubuntu.

**Comment by caoxiemeihao** [comment]
Hey👋 ! @Kilian 
Fixed this issue in `v0.28.4` (only use try-catch).
I only know that if he `pid` does not exist during the exec of `process.kill(pid)`, it will result in an `Error: kill ESRCH` error.
I can't full figure out why the `pid` exit early, but this not a very important matter.

**Comment by caoxiemeihao** [comment]
> Unfortunately this now has a different issue, where it crashes because vite:client-inject is no longer running?

This error looks like it comes from the renderer process build, can you make a minimal production repo form me?

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/vite-plugin-electron/issues/251#issuecomment-2360153184
Maybe this will work for you.

**Comment by Akryum** [comment]
> [#251 (comment)](https://github.com/electron-vite/vite-plugin-electron/issues/251#issuecomment-2360153184) Maybe this will work for you.

I have the problem and using process.kill like in the linked comment worked.

What I had when saving a electron file:

```
build started...
✓ 0 modules transformed.
[vite:esbuild-transpile] The service is no longer running: write EPIPE
```

**Comment by subframe7536** [comment]
Close for stale, feel free to reopen
