### ISSUE TITLE
__dirname is not defined in ES module scope

### ISSUE THREAD

**Issue by ParadiseWitch** [electron-vite/vite-plugin-electron#258]
I used the `playwright` times error on the electron main thread:
```sh
App threw an error during load
ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '...\my-electron-vite-project\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///.../my-electron-vite-project/dist-electron/main.js:2187:136
    at file:///.../my-electron-vite-project/dist-electron/main.js:88:33
    at file:///.../my-electron-vite-project/dist-electron/main.js:8292:133
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadApplicationPackage (file:///.../my-electron-vite-project/node_modules/electron/dist/resources/default_app.asar/main.js:129:9)
    at async file:///.../my-electron-vite-project/node_modules/electron/dist/resources/default_app.asar/main.js:241:9
```
[minimum-reproduction](https://github.com/ParadiseWitch/my-electron-vite-project-minimum-reproduction)

**Comment by foxypiratecove37350** [comment]
`__dirname` is a CommonJS feature, you can replicate it in ESM using that:

```ts
import path from 'path'

const __dirname = path.dirname(new URL(import.meta.url).pathname)
```

**Comment by subframe7536** [comment]
Close for stale, feel free to reopen
