### ISSUE TITLE
🐞 Some errors in `playground/usecase-in-renderer`

### ISSUE THREAD

**Issue by luo10** [electron-vite/vite-plugin-electron#40]
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (/Volumes/geek+/www/flexible-assistant-client/node_modules/webpack/lib/NormalModule.js:976:19)
    at /Volumes/geek+/www/flexible-assistant-client/node_modules/webpack/lib/NormalModule.js:1095:5
    at processResult (/Volumes/geek+/www/flexible-assistant-client/node_modules/webpack/lib/NormalModule.js:800:11)
    at /Volumes/geek+/www/flexible-assistant-client/node_modules/webpack/lib/NormalModule.js:860:5
    at /Volumes/geek+/www/flexible-assistant-client/node_modules/loader-runner/lib/LoaderRunner.js:407:3
    at iterateNormalLoaders (/Volumes/geek+/www/flexible-assistant-client/node_modules/loader-runner/lib/LoaderRunner.js:233:10)
    at /Volumes/geek+/www/flexible-assistant-client/node_modules/loader-runner/lib/LoaderRunner.js:224:4
    at /Volumes/geek+/www/flexible-assistant-client/node_modules/webpack/lib/NormalModule.js:834:15
    at Array.eval (eval at create (/Volumes/geek+/www/flexible-assistant-client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at runCallbacks (/Volumes/geek+/www/flexible-assistant-client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)

[vite-plugin-esmodule] build failed.

**Comment by caoxiemeihao** [comment]
提供下 Demo
