### ISSUE TITLE
ERR_REQUIRE_ESM after upgrading to v0.8.5

### ISSUE THREAD

**Issue by Eventect** [electron-vite/vite-plugin-electron#52]
Steps to reproduce:
1. Clone https://github.com/electron-vite/electron-vite-react
2. Upgrade vite-plugin-electron to v0.8.5
3. Error:
`
failed to load config from /Users/higgihs/Sites/Test/electron-vite-react/vite.config.ts
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/higgihs/Sites/Test/electron-vite-react/node_modules/vite-plugin-electron/dist/index.js from /Users/higgihs/Sites/Test/electron-vite-react/vite.config.ts not supported.
Instead change the require of index.js in /Users/higgihs/Sites/Test/electron-vite-react/vite.config.ts to a dynamic import() which is available in all CommonJS modules.
    at Object._require.extensions.<computed> [as .js] (file:///Users/higgihs/Sites/Test/electron-vite-react/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62910:17)
    at Object.<anonymous> (/Users/higgihs/Sites/Test/electron-vite-react/vite.config.ts:36:43)
    at Object._require.extensions.<computed> [as .js] (file:///Users/higgihs/Sites/Test/electron-vite-react/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62907:24)
    at loadConfigFromBundledFile (file:///Users/higgihs/Sites/Test/electron-vite-react/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62915:21)
    at loadConfigFromFile (file:///Users/higgihs/Sites/Test/electron-vite-react/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62780:34)
    at async resolveConfig (file:///Users/higgihs/Sites/Test/electron-vite-react/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62398:28)
    at async createServer (file:///Users/higgihs/Sites/Test/electron-vite-react/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:59018:20)
    at async CAC.<anonymous> (file:///Users/higgihs/Sites/Test/electron-vite-react/node_modules/vite/dist/node/cli.js:699:24)
`

4. Downgrading to v0.8.4 solves the problem

**Comment by caoxiemeihao** [comment]
You can upgrading to `v0.8.6`
