### ISSUE TITLE
importing electron in a WebWorker doesn't work

### ISSUE THREAD

**Issue by astoilkov** [electron-vite/vite-plugin-electron#69]
Doing `import { ipcRenderer} from 'electron'` (or any other renderer electron module) crashes the app with `reason: "crashed"` and `exitCode: 11`.

## Details

- I'm trying to migrate from Webpack and the same code works there.
- `nodeIntegrationInWorker` is set to true.
- Exit code 11 usually means [Segmentation fault](https://en.wikipedia.org/wiki/Segmentation_fault).
- One thing that is being logged in the Terminal when the app crashes:
    ```
  [20890:0831/172750.464535:ERROR:shared_image_manager.cc(267)] SharedImageManager::ProduceOverlay: Trying to Produce a Overlay representation from a non-existent mailbox.
  [20890:0831/172750.464559:ERROR:skia_output_device_buffer_queue.cc(354)] Invalid mailbox.
  [20890:0831/172750.464564:ERROR:shared_image_manager.cc(267)] SharedImageManager::ProduceOverlay: Trying to Produce a Overlay representation from a non-existent mailbox.
  [20890:0831/172750.464569:ERROR:skia_output_device_buffer_queue.cc(354)] Invalid mailbox.
  [20890:0831/172750.464572:ERROR:shared_image_manager.cc(267)] SharedImageManager::ProduceOverlay: Trying to Produce a Overlay representation from a non-existent mailbox.
  [20890:0831/172750.464578:ERROR:skia_output_device_buffer_queue.cc(354)] Invalid mailbox.
  [20890:0831/172750.464580:ERROR:shared_image_manager.cc(267)] SharedImageManager::ProduceOverlay: Trying to Produce a Overlay representation from a non-existent mailbox.
  [20890:0831/172750.464584:ERROR:skia_output_device_buffer_queue.cc(354)] Invalid mailbox.
  [20890:0831/172750.464601:ERROR:shared_image_manager.cc(267)] SharedImageManager::ProduceOverlay: Trying to Produce a Overlay representation from a non-existent mailbox.
  [20890:0831/172750.464606:ERROR:skia_output_device_buffer_queue.cc(354)] Invalid mailbox.
  [20890:0831/172750.464609:ERROR:shared_image_manager.cc(267)] SharedImageManager::ProduceOverlay: Trying to Produce a Overlay representation from a non-existent mailbox.
  [20890:0831/172750.464612:ERROR:skia_output_device_buffer_queue.cc(354)] Invalid mailbox.
  ```
- Another thing:
  ```
  Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
      at n._sendInternal (node:electron/js2c/browser_init:165:629)
      at b._sendInternal (node:electron/js2c/browser_init:161:2573)
      at node:electron/js2c/browser_init:193:729
      at new Promise (<anonymous>)
      at Object.invokeInWebContents (node:electron/js2c/browser_init:193:477)
      at b.executeJavaScript (node:electron/js2c/browser_init:161:3267)
      at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
  ```

**Comment by astoilkov** [comment]
I think that's the reason for the crash: https://github.com/electron/electron/pull/35422.

Closing this issue. Sorry for incorrectly reporting it here.

**Comment by astoilkov** [comment]
Was wrong about it. Upgrading Electron to the latest doesn't fix the problem. The problem is somewhere else.

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction Demo?

**Comment by astoilkov** [comment]
Yes. I will start working on building a reproducible demo.

Did you try to import and call an electron module in a WebWorker (loaded with `type: "module"`)? Does it work for you?

**Comment by caoxiemeihao** [comment]
`type: "module"` will be supported in `v0.9.3`, coming soon. 🚚

**Comment by astoilkov** [comment]
Great! So, for now, there is no need for me to create a reproducible demo, right?

**Comment by caoxiemeihao** [comment]
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/26263658/188083711-2f60a46b-a2d0-414c-9a0c-e57fa7bafa3e.png">
There's something wrong with building esm support, I'm trying to Debug Vite and it's confusing.
Or I'll use Rollup to get around this.
Sorry for the wait.

**Comment by astoilkov** [comment]
A little context (it might be useful for you):
- I don't get any error from Vite when using `type: "module"` when creating a new WebWorker.
- `import something from 'module'` doesn't work if I don't set the `type: "module"`.

I also may use WebWorker without `type: "module"` but I'm not sure how should I import stuff. Maybe it's not possible?

**Comment by caoxiemeihao** [comment]
`type: "module"` doesn't work with Electron, probably because Electron doesn't support ESM well.
I built the ESM version of the plugin, but Electron doesn't work when `type: "module"` is enabled.

Support `type: "module"` branch 👉 [vite-plugin-electron/tree/type-module](https://github.com/electron-vite/vite-plugin-electron/tree/type-module)

Run setup

```bash
cd playground/usecase-in-main

npm run dev
```

Errors

```log
App threw an error during load
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/atom/Desktop/github/vite-plugin-electron/playground/usecase-in-main/dist/electron/main/index.js from /Users/atom/Desktop/github/vite-plugin-electron/node_modules/.pnpm/electron@19.0.8/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js not supported.
Instead change the require of index.js in /Users/atom/Desktop/github/vite-plugin-electron/node_modules/.pnpm/electron@19.0.8/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js to a dynamic import() which is available in all CommonJS modules.
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at loadApplicationPackage (/Users/atom/Desktop/github/vite-plugin-electron/node_modules/.pnpm/electron@19.0.8/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:110:16)
    at Object.<anonymous> (/Users/atom/Desktop/github/vite-plugin-electron/node_modules/.pnpm/electron@19.0.8/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:222:9)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Object.<anonymous> (node:electron/js2c/browser_init:185:3104)
    at ./lib/browser/init.ts (node:electron/js2c/browser_init:185:3308)
    at __webpack_require__ (node:electron/js2c/browser_init:1:128)
    at node:electron/js2c/browser_init:1:1200
    at node:electron/js2c/browser_init:1:1267
    at c._load (node:electron/js2c/asar_bundle:5:13343)
```

**Comment by astoilkov** [comment]
I'm creating the WebWorker from the renderer process. Is this relevant?

**Comment by caoxiemeihao** [comment]
still hope you provide a minimal Demo 😄

**Comment by astoilkov** [comment]
Yep, I will do it on Monday.

**Comment by Jazcash** [comment]
I'm in the process of swapping from webpack to vite, and one of the issues I have atm is the production build is crashing when trying to use nodejs modules, but works fine in development.

e.g.

`index.ts`:
```
import TestWorker from "@/workers/test-worker?worker";
const testWorker = new TestWorker();
```

`workers/test-worker.ts`:
```
import * as path from "path";
console.log(path.parse(__dirname));
```

I have `nodeIntegrationInWorker: true`, and as I said it works fine in development, but in the production build it doesn't recognise the path module and the built worker file looks a little sketchy:

![image](https://user-images.githubusercontent.com/1434248/188284941-b9133ab0-3d3c-462e-a5ad-9abf15367860.png)

Is this the right issue to report this? Am curious if the work you're doing will fix this or if my issue is unrelated.

**Comment by caoxiemeihao** [comment]
This project is just for my personal interest, I have not tested many cases, such as `web worder`.
By the way, Vite behaves very differently during development and build, so I run into really tricky issues a lot of the time.

**Comment by astoilkov** [comment]
Done. Here is the repo: https://github.com/astoilkov/electron-vite-worker-issue.

The important part is in `renderer/main.ts`:
```ts
document.body.addEventListener('click', () => {
  new Worker(new URL('./worker.ts', import.meta.url), {
    type: 'module'
  })
})
```

Clicking on the "hello" text will run the code and the `BrowserWindow` will crash. You can open DevTools before you click the "hello" text so you can see DevTools shows a message as well.

**Comment by caoxiemeihao** [comment]
@astoilkov 👋
Eventually, I found that using `ipcRenderer` in a Web Worker would cause the Electron-Renderer to crash. This is confusing!
https://github.com/astoilkov/electron-vite-worker-issue/pull/1
I submitted a PR to try to bypass access to ipcRenderer.

**Comment by astoilkov** [comment]
Great, thanks! Are you going to implement a fix in electron-vite-renderer?

**Comment by caoxiemeihao** [comment]
This problem may come from Electron itself, what we can do is to hide `ipcRenderer` when using electron module in Web Worker. Not sure if this is the right thing to do or if we need to state this in the README.md. 🤔

**Comment by astoilkov** [comment]
I think you can safely hide `ipcRenderer` in Web Worker because it seems, as I learned just now, that you shouldn't access it and the behavior is expected because there isn't a `webFrame` inside of workers — https://github.com/electron/electron/issues/34992.

**Comment by caoxiemeihao** [comment]
Good idea! I will fix it in next version. 🚚

**Comment by astoilkov** [comment]
Another idea: You can throw an error if someone tries to access an ipcRenderer property (using a Proxy) and explain the issue. This will be very helpful to other users.

**Comment by caoxiemeihao** [comment]
@astoilkov 👋
Now, `v0.9.3` is available.

**Comment by astoilkov** [comment]
Awesome! Thanks for all the work you put into this!
