### ISSUE TITLE
Getting "Could not resolve entry module (index.html)" on 0.10.2

### ISSUE THREAD

**Issue by evil-shrike** [electron-vite/vite-plugin-electron#97]
After I've upgraded `vite` to 3.2 from 3.1 I **and** `vite-plugin-electron` to 0.10.2, I started getting an error: 'Could not resolve entry module (index.html)":

```
vite v3.2.0 building for production...
✓ 0 modules transformed.
Could not resolve entry module (index.html).
error during build:
Error: Could not resolve entry module (index.html).
    at error (file:///Users/user/work/workbench-vite-bug/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at ModuleLoader.loadEntryModule (file:///Users/user/work/workbench-vite-bug/node_modules/rollup/dist/es/shared/rollup.js:22175:20)
    at async Promise.all (index 0)
```

If I remove `electron` plugin from vite.config.ts the error goes away (at first I thought it's coming from vite@3.2 but it doesn't look so).
If I install 0.9.3 version the error goes away as well.

vite.config.ts:
```
import {fileURLToPath, URL} from 'node:url';
import {rmSync} from 'fs';
import path from 'path';
import {defineConfig} from 'vite';
import vue from '@vitejs/plugin-vue';
import pkg from './package.json';
import electron, {onstart} from 'vite-plugin-electron';

// https://vitejs.dev/config/
export default defineConfig({
  root: 'src',
  base: path.resolve(__dirname, "./dist/"),
  plugins: [
    vue(),
    electron({
      main: {
        entry: 'src/electron/main/index.ts',
        vite: {
          build: {
            sourcemap: true,
            outDir: 'dist/electron/main',
          },
          plugins: [process.env.VSCODE_DEBUG ? onstart() : null],
        },
      },
      preload: {
        input: {
          index: path.join(__dirname, 'src/electron/preload/index.ts'),
        },
        vite: {
          build: {
            sourcemap: 'inline',
            outDir: 'dist/electron/preload',
          },
        },
      },
    }),
  ],
  server: process.env.VSCODE_DEBUG
    ? {
        host: pkg.debug.env.VITE_DEV_SERVER_HOSTNAME,
        port: pkg.debug.env.VITE_DEV_SERVER_PORT,
      }
    : undefined,
  build: {
    rollupOptions: {
      input: {
        app: './src/index.html',
      },
    },
    outDir: '../dist'
  },
});
```

My index.html is inside src folder:
```
|-- electron-builder.json5
|-- package-lock.json
|-- package.json
|-- src
|   |-- electron
|   |   |-- electron-env.d.ts
|   |   |-- main
|   |   |   `-- index.ts
|   |   `-- preload
|   |       `-- index.ts
|   |-- index.html
|   `-- web
|       |-- App.vue
|       |-- electron.d.ts
|       |-- env.d.ts
|       `-- main.ts
|-- tsconfig.json
|-- tsconfig.node.json
`-- vite.config.ts
```

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/vite-plugin-electron/blob/v0.10.0/CHANGELOG.md

**Comment by evil-shrike** [comment]
thanks,
but it's not quite clear what's changed. As I understood from the changelog, `main` and `preload` sections have gone and now it's just an array of entries. But how is it related to index.html?

here's my updated vite.config:
```
  plugins: [
    vue(),
    electron([
      {
        entry: 'src/electron/main/index.ts',
        vite: {
          build: {
            sourcemap: true,
            outDir: 'dist/electron/main',
          },
          plugins: [process.env.VSCODE_DEBUG ? onstart() : null],
        },
      },
      {
        input: {
          index: path.join(__dirname, 'src/electron/preload/index.ts'),
        },
        vite: {
          build: {
            sourcemap: 'inline',
            outDir: 'dist/electron/preload',
          },
        },
      },
    ]),
  ],
```

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/vite-plugin-electron/blob/main/examples/quick-start/vite.config.ts

**Comment by caoxiemeihao** [comment]
Hi! 👋 Do you work at Google? In the US?

**Comment by evil-shrike** [comment]
@caoxiemeihao yes, I do, but not in the US.

**Comment by caoxiemeihao** [comment]
Is it remote work？

**Comment by evil-shrike** [comment]
No, it's not. Why?

**Comment by caoxiemeihao** [comment]
It must be a good job with more pay :)
